services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ENV: development
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/app?sslmode=disable
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8081:80"
    depends_on:
      api:
        condition: service_started

  migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://postgres:postgres@postgres:5432/app?sslmode=disable"
      - "up"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
